export enum SheetStatus {
  SUBMITTED = "SUBMITTED",
  SEMI_SUBMITTED = "SEMI_SUBMITTED",
  APPROVED = "APPROVED",
  SEMI_APPROVED = "SEMI_APPROVED",
  REJECTED = "REJECTED",
  SEMI_REJECTED = "SEMI_REJECTED",
  DELAYED = "DELAYED",
  SEMI_DELAYED = "SEMI_DELAYED",
  NEW = "NEW",
}
